/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BfsGraph {
  one(source: number): BfsOneResult
  batch(sources: Array<number>): BfsBatchResult
  all(): BfsBatchResult
  path(source: number, target: number): BfsPathResult
  oneHistogram(source: number): BfsHistogramResult
  batchHistogram(sources: Array<number>): BfsHistogramBatchResult
  allHistogram(): BfsHistogramBatchResult
  mergedHistogram(): MergedHistogram
}

export declare function bfsAll(adj: Array<number>, offsets: Array<number>, n: number): BfsBatchResult

export declare function bfsAllHistogram(adj: Array<number>, offsets: Array<number>, n: number): BfsHistogramBatchResult

export declare function bfsBatch(adj: Array<number>, offsets: Array<number>, n: number, sources: Array<number>): BfsBatchResult

export declare function bfsBatchHistogram(adj: Array<number>, offsets: Array<number>, n: number, sources: Array<number>): BfsHistogramBatchResult

export interface BfsBatchResult {
  results: Array<BfsOneResult>
  processed: number
}

export interface BfsHistogramBatchResult {
  results: Array<BfsHistogramResult>
  processed: number
}

export interface BfsHistogramResult {
  histogram: Array<number>
  maxDistance: number
}

export declare function bfsMergedHistogram(adj: Array<number>, offsets: Array<number>, n: number): MergedHistogram

export declare function bfsOne(adj: Array<number>, offsets: Array<number>, n: number, source: number): BfsOneResult

export declare function bfsOneHistogram(adj: Array<number>, offsets: Array<number>, n: number, source: number): BfsHistogramResult

export interface BfsOneResult {
  distances: Array<number>
  maxDistance: number
  histogram: Array<number>
}

export declare function bfsPath(adj: Array<number>, offsets: Array<number>, n: number, source: number, target: number): BfsPathResult

export interface BfsPathResult {
  path: Array<number>
  distance: number
}

export declare function createBfsGraph(adj: Uint32Array, offsets: Uint32Array, n: number): BfsGraph

export interface MergedHistogram {
  histogram: Array<number>
  maxDistance: number
}
