/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 从所有节点并行执行 BFS（全量） */
export declare function bfsAll(adj: Array<number>, offsets: Array<number>, n: number): BfsBatchResult

/**
 * 从多个源节点并行执行 BFS
 *
 * # 参数
 * * `adj` - 邻接表，所有邻居节点 ID 平铺
 * * `offsets` - 每个节点在 adj 中的起始偏移，长度为 n + 1，最后一项为 adj 的长度
 * * `n` - 总节点数
 * * `sources` - 需要执行 BFS 的源节点 ID 列表
 */
export declare function bfsBatch(adj: Array<number>, offsets: Array<number>, n: number, sources: Array<number>): BfsBatchResult

/** 批量 BFS 结果 */
export interface BfsBatchResult {
  /** 每个源节点的 BFS 结果 */
  results: Array<BfsOneResult>
  /** 成功处理的源节点数 */
  processed: number
}

/** 从单个源节点执行 BFS，返回距离数组 */
export declare function bfsOne(adj: Array<number>, offsets: Array<number>, n: number, source: number): BfsOneResult

/** 单源 BFS 结果 */
export interface BfsOneResult {
  /** 源节点到每个节点的最短距离（-1 表示不可达） */
  distances: Array<number>
  /** 最大有限距离 */
  maxDistance: number
  /** 距离直方图：histogram[d] = 距离为 d 的节点数（不含源节点自身） */
  histogram: Array<number>
}

/**
 * 计算从 source 到 target 的最短路径（BFS + 父节点回溯）
 *
 * 找到 target 时立即终止，不遍历全图。
 * 不可达时 path 为空数组，distance 为 -1。
 */
export declare function bfsPath(adj: Array<number>, offsets: Array<number>, n: number, source: number, target: number): BfsPathResult

/** 最短路径结果 */
export interface BfsPathResult {
  /** 从 source 到 target 的最短路径节点序列（含两端），不可达时为空数组 */
  path: Array<number>
  /** 路径长度（边数），不可达时为 -1 */
  distance: number
}
